### ISSUE TITLE
使用 vite-plugin-vue3-bem 插件报错

### ISSUE THREAD

**Issue by rockliuxn** [KesionX/vue3-bem#2]
![image](https://github.com/KesionX/vue3-bem/assets/7591665/bf8ef04a-21a1-48fb-ad8f-348719118e7f)

按照文档在vite.config.ts 配置了 ‘vite-plugin-vue3-bem’  插件，但启动时报错 ：‘ ViteVue3Bem is not a function ’

**Comment by nick-shaydayuk** [comment]
@rockliuxn i use ssr rendering and got same issue, have you found any solutions?

**Comment by rockliuxn** [comment]
@nick-shaydayuk I have given up using it and embraced UnoCSS.
